### ISSUE TITLE
Incluir metadados padrão para uso em clusters

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/bvs-aps#20]
Serão definidos alguns metadados padrão a serem acrescentados nos registros XML de SOF e PEARLS para que os mesmos sejam filtrados por outros clusters. Por exemplo, todos serão marcados por idioma "pt". SCI fornecerá esta informação.

**Comment by wilsonmoura** [comment]
Versão antiga do tema da BVS APS. Nova versão disponível em https://github.com/bireme/wordptress-themes
