### ISSUE TITLE
Ajustar o rodapé das páginas secundárias da BVS APS

### ISSUE THREAD

**Issue by sousajul** [bireme/bvs-aps#30]
Solicito apoio para ajustar o rodapé das páginas secundarias da BVS APS, deixar igual da home.

Home:

![image](https://user-images.githubusercontent.com/13439949/204563528-bb660ff2-bffc-4f19-8710-ff8924cb14b8.png)

Páginas secundarias (https://aps.bvs.br/sobre/):
![image](https://user-images.githubusercontent.com/13439949/204563711-32b731a1-0bbe-492d-bcd0-c73f50d73209.png)

**Comment by marcioalvessilva** [comment]
@sousajul por favor validar.
Junto com @wilsonmoura detectamos que existe uma condição para escolher qual rodapé seria utilizado na home e no template de páginas, @wilsonmoura criou uma condição para que fosse utilizado o mesmo para os dois caminhos.

**Comment by sousajul** [comment]
Validado, podem passar para produção. Att.
